name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 74-upgrade-welcome-clerk-to-new-home-and-time-opening-up-for-current-development
      - 'releases/*'

jobs:
  qodana-welcome-clerk-quality-scan:
    runs-on: self-hosted

    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4.2.1
        name: 'Checkout Welcome Clerk codebase'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: JetBrains/qodana-action@v2024.2
        name: 'Execute Qodana Scan from repository root'
        with:
          pr-mode: false
          push-fixes: pull_request
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1038502248 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
